name: Fetch Discogs Collection Daily

on:
  schedule:
    # Draait elke dag om 05:00 UTC (pas eventueel aan naar wens)
    # Voorbeeld: '0 7 * * *' voor 07:00 UTC (is 8:00 of 9:00 Nederlandse tijd, afh. van zomer/wintertijd)
    - cron: '0 5 * * *'
  workflow_dispatch: # Maakt handmatig draaien mogelijk via de Actions tab

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest # Gebruik een standaard Linux runner
    permissions:
      contents: write # Geef toestemming om code te committen/pushen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Haalt je code op

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Gebruik een recente Python 3 versie
          # GEEN 'cache: pip' hier, om de foutmelding over requirements.txt te vermijden

      - name: Install dependencies
        # Installeer de benodigde library direct, zonder requirements.txt
        run: pip install requests

      - name: Run Python script to fetch Discogs data
        env:
          # Geef de secrets door als omgevingsvariabelen aan het script
          DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
          DISCOGS_USERNAME: ${{ secrets.DISCOGS_USERNAME }}
        # Zorg dat je Python script 'fetch_discogs.py' heet en in de root van je repo staat
        run: python fetch_discogs.py

      - name: Commit and push if changes
        # Gebruikt een action die het committen/pushen versimpelt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Discogs collection data" # Het commit bericht
          file_pattern: src/data/cd_collection.json # Alleen dit bestand committen als het gewijzigd is
          commit_user_name: "GitHub Actions Bot" # Naam van de committer
          commit_user_email: "actions@github.com" # E-mail van de committer
          commit_author: "GitHub Actions Bot <actions@github.com>" # Auteur van de commit
          # Voeg eventueel branch toe als je niet naar 'main' of 'master' pusht:
          # branch: jouw-branch-naam
