on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Haal repo op
        uses: actions/checkout@v3

      - name: Installeer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installeer dependencies
        run: pip install requests beautifulsoup4

      - name: Draai scraper script
        run: python scraper.py  # Zorg dat scraper.py data opslaat in JSON

      - name: Commit en push data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update Kruidvat data"
          git push
